package cli

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestIrcLog2SessionsGolden renders testdata/chat.log and compares every
// produced file byte-for-byte with testdata/sessions_golden/, which was
// generated by the retired Python tools/irclog2sessions.py. This pins the Go
// port to the Python output so reruns never churn committed session docs.
// checkSessionMatchesGolden asserts that the rendered session file for name
// equals the golden fixture under testdata/sessions_golden/.
func checkSessionMatchesGolden(t *testing.T, outDir, goldenDir string) {
	t.Helper()
	name := filepath.Base(goldenDir)
	want, err := os.ReadFile(filepath.Join(goldenDir, "session.md"))
	if err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(outDir, "session-"+name+".md"))
	if err != nil {
		t.Errorf("session %s: %v", name, err)
		return
	}
	if !bytes.Equal(got, want) {
		t.Errorf("session %s differs from Python golden:\ngot:\n%s\nwant:\n%s", name, got, want)
	}
}

// checkNoCredentialLeak asserts that the NickServ IDENTIFY line and replayed
// user-output never appear in any rendered session file.
func checkNoCredentialLeak(t *testing.T, files []string) {
	t.Helper()
	for _, file := range files {
		data, err := os.ReadFile(file)
		if err != nil {
			t.Fatal(err)
		}
		if bytes.Contains(data, []byte("supersecret")) {
			t.Errorf("credential leaked into %s", file)
		}
		if bytes.Contains(data, []byte("replayed dupe")) {
			t.Errorf("useroutput replay leaked into %s", file)
		}
	}
}

func TestIrcLog2SessionsGolden(t *testing.T) {
	outDir := t.TempDir()
	var buf bytes.Buffer
	if err := IrcLog2SessionsCmd([]string{"testdata/chat.log", "--out", outDir, "--include-open", "--timezone=UTC"}, &buf); err != nil {
		t.Fatal(err)
	}

	goldenDirs, err := filepath.Glob("testdata/sessions_golden/*")
	if err != nil {
		t.Fatal(err)
	}
	if len(goldenDirs) == 0 {
		t.Fatal("no golden session dirs found")
	}
	for _, goldenDir := range goldenDirs {
		checkSessionMatchesGolden(t, outDir, goldenDir)
	}

	gotFiles, err := filepath.Glob(filepath.Join(outDir, "session-*.md"))
	if err != nil {
		t.Fatal(err)
	}
	if len(gotFiles) != len(goldenDirs) {
		t.Errorf("wrote %d session files, want %d", len(gotFiles), len(goldenDirs))
	}
	if got := strings.Count(buf.String(), "wrote "); got != len(goldenDirs) {
		t.Errorf("printed %d 'wrote' lines, want %d", got, len(goldenDirs))
	}
	checkNoCredentialLeak(t, gotFiles)
}

// Without --include-open, the trailing session of the channel with the newest
// event is within one gap of the end of the log and must be skipped.
func TestIrcLog2SessionsSkipsOpenSession(t *testing.T) {
	outDir := t.TempDir()
	var buf bytes.Buffer
	err := IrcLog2SessionsCmd([]string{"testdata/chat.log", "--out", outDir, "--timezone=UTC"}, &buf)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(outDir, "session-2026-06-11-ccrep-ccrep-titled-session.md")); !os.IsNotExist(err) {
		t.Errorf("open trailing session was rendered, want skipped (stat err: %v)", err)
	}
	if !strings.Contains(buf.String(), "skipped 1 possibly-open session(s); use --include-open to render anyway") {
		t.Errorf("missing skip notice in output:\n%s", buf.String())
	}
}

func TestIrcLog2SessionsChannelFilter(t *testing.T) {
	outDir := t.TempDir()
	var buf bytes.Buffer
	err := IrcLog2SessionsCmd([]string{"testdata/chat.log", "--out", outDir,
		"--channel", "#CCREP", "--include-open", "--timezone=UTC"}, &buf)
	if err != nil {
		t.Fatal(err)
	}
	files, err := filepath.Glob(filepath.Join(outDir, "session-*.md"))
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 2 {
		t.Fatalf("got %d session files %v, want 2 #ccrep sessions", len(files), files)
	}
	for _, file := range files {
		if !strings.Contains(filepath.Base(file), "ccrep") {
			t.Errorf("unexpected non-#ccrep session %s", file)
		}
	}
}

func TestIrcLog2SessionsNoEvents(t *testing.T) {
	empty := filepath.Join(t.TempDir(), "chat.log")
	if err := os.WriteFile(empty, []byte("not a chat.log line\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	err := IrcLog2SessionsCmd([]string{empty, "--out", t.TempDir(), "--timezone=UTC"}, &bytes.Buffer{})
	if err == nil || !strings.Contains(err.Error(), "no channel events found") {
		t.Fatalf("err = %v, want 'no channel events found'", err)
	}
}

func TestSlugify(t *testing.T) {
	cases := []struct{ in, want string }{
		{"Go port kickoff", "go-port-kickoff"},
		{"  !!weird?? punctuation  ", "weird-punctuation"},
		{"!!!", ""},
		{"A very long topic title that should be truncated at forty eight characters exactly",
			"a-very-long-topic-title-that-should-be-truncated"},
	}
	for _, c := range cases {
		if got := slugify(c.in); got != c.want {
			t.Errorf("slugify(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestParseIRCCommand(t *testing.T) {
	cases := []struct {
		raw                 string
		channel, kind, text string
		ok                  bool
	}{
		{"PRIVMSG #botfam :hello there", "#botfam", "message", "hello there", true},
		{"privmsg #botfam no-colon text", "#botfam", "message", "no-colon text", true},
		{"NOTICE #botfam :heads up", "#botfam", "notice", "heads up", true},
		{"PRIVMSG #botfam :\x01ACTION waves\x01", "#botfam", "action", "waves", true},
		{"PRIVMSG #botfam :\x01ACTION no trailing delimiter", "#botfam", "action", "no trailing delimiter", true},
		{"PRIVMSG NickServ :IDENTIFY hunter2", "", "", "", false},
		{"PASS hunter2", "", "", "", false},
		{"JOIN #foo,#bar somekey", "#foo", "join", "", true},
		{"PART #botfam :bye", "#botfam", "part", "", true},
		{"TOPIC #botfam :new topic", "#botfam", "topic", "new topic", true},
		{"TOPIC #botfam", "", "", "", false}, // bare query, no payload
		{"PING server", "", "", "", false},
	}
	for _, c := range cases {
		channel, kind, text, ok := parseIRCCommand(c.raw)
		if channel != c.channel || kind != c.kind || text != c.text || ok != c.ok {
			t.Errorf("parseIRCCommand(%q) = (%q, %q, %q, %v), want (%q, %q, %q, %v)",
				c.raw, channel, kind, text, ok, c.channel, c.kind, c.text, c.ok)
		}
	}
}
