package metareview

import (
	"fmt"
	"strings"
)

// commentHeader is the fixed preamble; it asserts the independence the skill
// requires (the meta-review did not see the primary verdict).
const commentHeader = `## Risk meta-review (advisory)

Isolated per-artifact pass by the ollama meta-review driver. Independent of the
primary review — this did not see the primary verdict.`

// ComposeComment renders the single advisory comment from confirmed
// suggestions, in the skill's machine-parseable table format. modelTag (e.g.
// "ollama:qwen2.5-coder seed=42") goes in the footer so the Stage-2 label
// corpus can attribute and reproduce each suggestion.
func ComposeComment(suggestions []Suggestion, modelTag string) string {
	var b strings.Builder
	b.WriteString(commentHeader)
	b.WriteString("\n\n")

	if len(suggestions) == 0 {
		b.WriteString("No per-artifact risks found.\n")
	} else {
		b.WriteString("| suggested label | confidence | evidence | triage |\n")
		b.WriteString("| :--- | :--- | :--- | :--- |\n")
		for _, s := range suggestions {
			triage := suggestedTriage[s.Label]
			if triage == "" {
				triage = "—"
			}
			fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", s.Label, s.Confidence, escapePipes(s.Evidence), triage)
		}
	}

	fmt.Fprintf(&b, "\n<sub>generated by `botfam meta-review` (%s); advisory — the author/triager confirms. See skill `meta-review`.</sub>\n", modelTag)
	return b.String()
}

// escapePipes keeps a one-line evidence string from breaking the markdown table.
func escapePipes(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "|", "\\|"), "\n", " ")
}
