// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: botfam/eventdelivery/v2/eventdelivery.proto

package eventdeliveryv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoOwner     string                 `protobuf:"bytes,1,opt,name=repo_owner,json=repoOwner,proto3" json:"repo_owner,omitempty"`
	RepoName      string                 `protobuf:"bytes,2,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	MilestoneId   int64                  `protobuf:"varint,3,opt,name=milestone_id,json=milestoneId,proto3" json:"milestone_id,omitempty"`
	Labels        []string               `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{0}
}

func (x *Scope) GetRepoOwner() string {
	if x != nil {
		return x.RepoOwner
	}
	return ""
}

func (x *Scope) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *Scope) GetMilestoneId() int64 {
	if x != nil {
		return x.MilestoneId
	}
	return 0
}

func (x *Scope) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type SessionEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FencingToken  uint64                 `protobuf:"varint,5,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEndpoint) Reset() {
	*x = SessionEndpoint{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEndpoint) ProtoMessage() {}

func (x *SessionEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEndpoint.ProtoReflect.Descriptor instead.
func (*SessionEndpoint) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{1}
}

func (x *SessionEndpoint) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *SessionEndpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SessionEndpoint) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SessionEndpoint) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEndpoint) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

type AcquireRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Scope          *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	HolderIdentity string                 `protobuf:"bytes,2,opt,name=holder_identity,json=holderIdentity,proto3" json:"holder_identity,omitempty"`
	Ttl            *durationpb.Duration   `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcquireRequest) Reset() {
	*x = AcquireRequest{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireRequest) ProtoMessage() {}

func (x *AcquireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireRequest.ProtoReflect.Descriptor instead.
func (*AcquireRequest) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{2}
}

func (x *AcquireRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *AcquireRequest) GetHolderIdentity() string {
	if x != nil {
		return x.HolderIdentity
	}
	return ""
}

func (x *AcquireRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type RenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewRequest) Reset() {
	*x = RenewRequest{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRequest) ProtoMessage() {}

func (x *RenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRequest.ProtoReflect.Descriptor instead.
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{3}
}

func (x *RenewRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type Grant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granted       bool                   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	LeaseId       string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	FencingToken  uint64                 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grant) Reset() {
	*x = Grant{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grant) ProtoMessage() {}

func (x *Grant) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grant.ProtoReflect.Descriptor instead.
func (*Grant) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{5}
}

func (x *Grant) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *Grant) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *Grant) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *Grant) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type WorkerStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStream) Reset() {
	*x = WorkerStream{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStream) ProtoMessage() {}

func (x *WorkerStream) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStream.ProtoReflect.Descriptor instead.
func (*WorkerStream) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{6}
}

func (x *WorkerStream) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerStream) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type WorkItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind            string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	SourceId        string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Title           string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Body            string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	ScopeGeneration uint64                 `protobuf:"varint,6,opt,name=scope_generation,json=scopeGeneration,proto3" json:"scope_generation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkItem) Reset() {
	*x = WorkItem{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkItem) ProtoMessage() {}

func (x *WorkItem) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkItem.ProtoReflect.Descriptor instead.
func (*WorkItem) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{7}
}

func (x *WorkItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WorkItem) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *WorkItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WorkItem) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *WorkItem) GetScopeGeneration() uint64 {
	if x != nil {
		return x.ScopeGeneration
	}
	return 0
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkItemId    string                 `protobuf:"bytes,1,opt,name=work_item_id,json=workItemId,proto3" json:"work_item_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Uri           string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{8}
}

func (x *Artifact) GetWorkItemId() string {
	if x != nil {
		return x.WorkItemId
	}
	return ""
}

func (x *Artifact) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Artifact) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Artifact) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type Span struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Component     string                 `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,5,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{9}
}

func (x *Span) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Span) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Span) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Span) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Span) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *Span) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ForgeAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkItemId    string                 `protobuf:"bytes,1,opt,name=work_item_id,json=workItemId,proto3" json:"work_item_id,omitempty"`
	ActionKey     string                 `protobuf:"bytes,2,opt,name=action_key,json=actionKey,proto3" json:"action_key,omitempty"`
	ToolName      string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,4,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgeAction) Reset() {
	*x = ForgeAction{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgeAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgeAction) ProtoMessage() {}

func (x *ForgeAction) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgeAction.ProtoReflect.Descriptor instead.
func (*ForgeAction) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{10}
}

func (x *ForgeAction) GetWorkItemId() string {
	if x != nil {
		return x.WorkItemId
	}
	return ""
}

func (x *ForgeAction) GetActionKey() string {
	if x != nil {
		return x.ActionKey
	}
	return ""
}

func (x *ForgeAction) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ForgeAction) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

type ActionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Committed     bool                   `protobuf:"varint,1,opt,name=committed,proto3" json:"committed,omitempty"`
	Deduped       bool                   `protobuf:"varint,2,opt,name=deduped,proto3" json:"deduped,omitempty"`
	OutboxId      string                 `protobuf:"bytes,3,opt,name=outbox_id,json=outboxId,proto3" json:"outbox_id,omitempty"`
	ResponseJson  string                 `protobuf:"bytes,4,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionAck) Reset() {
	*x = ActionAck{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionAck) ProtoMessage() {}

func (x *ActionAck) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionAck.ProtoReflect.Descriptor instead.
func (*ActionAck) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{11}
}

func (x *ActionAck) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

func (x *ActionAck) GetDeduped() bool {
	if x != nil {
		return x.Deduped
	}
	return false
}

func (x *ActionAck) GetOutboxId() string {
	if x != nil {
		return x.OutboxId
	}
	return ""
}

func (x *ActionAck) GetResponseJson() string {
	if x != nil {
		return x.ResponseJson
	}
	return ""
}

type ObserveRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Scope           *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	ScopeGeneration uint64                 `protobuf:"varint,2,opt,name=scope_generation,json=scopeGeneration,proto3" json:"scope_generation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ObserveRequest) Reset() {
	*x = ObserveRequest{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveRequest) ProtoMessage() {}

func (x *ObserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveRequest.ProtoReflect.Descriptor instead.
func (*ObserveRequest) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{12}
}

func (x *ObserveRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *ObserveRequest) GetScopeGeneration() uint64 {
	if x != nil {
		return x.ScopeGeneration
	}
	return 0
}

type RawObservation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source         string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Repo           string                 `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	ArtifactKind   string                 `protobuf:"bytes,4,opt,name=artifact_kind,json=artifactKind,proto3" json:"artifact_kind,omitempty"`
	ArtifactNumber int64                  `protobuf:"varint,5,opt,name=artifact_number,json=artifactNumber,proto3" json:"artifact_number,omitempty"`
	EventKind      string                 `protobuf:"bytes,6,opt,name=event_kind,json=eventKind,proto3" json:"event_kind,omitempty"`
	EventKey       string                 `protobuf:"bytes,7,opt,name=event_key,json=eventKey,proto3" json:"event_key,omitempty"`
	SourceQuery    string                 `protobuf:"bytes,8,opt,name=source_query,json=sourceQuery,proto3" json:"source_query,omitempty"`
	PayloadJson    string                 `protobuf:"bytes,9,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	ObservedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RawObservation) Reset() {
	*x = RawObservation{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawObservation) ProtoMessage() {}

func (x *RawObservation) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawObservation.ProtoReflect.Descriptor instead.
func (*RawObservation) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{13}
}

func (x *RawObservation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RawObservation) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RawObservation) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *RawObservation) GetArtifactKind() string {
	if x != nil {
		return x.ArtifactKind
	}
	return ""
}

func (x *RawObservation) GetArtifactNumber() int64 {
	if x != nil {
		return x.ArtifactNumber
	}
	return 0
}

func (x *RawObservation) GetEventKind() string {
	if x != nil {
		return x.EventKind
	}
	return ""
}

func (x *RawObservation) GetEventKey() string {
	if x != nil {
		return x.EventKey
	}
	return ""
}

func (x *RawObservation) GetSourceQuery() string {
	if x != nil {
		return x.SourceQuery
	}
	return ""
}

func (x *RawObservation) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *RawObservation) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

type ProcessedMark struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RawObservationId string                 `protobuf:"bytes,1,opt,name=raw_observation_id,json=rawObservationId,proto3" json:"raw_observation_id,omitempty"`
	TranslationBatch string                 `protobuf:"bytes,2,opt,name=translation_batch,json=translationBatch,proto3" json:"translation_batch,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessedMark) Reset() {
	*x = ProcessedMark{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedMark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedMark) ProtoMessage() {}

func (x *ProcessedMark) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedMark.ProtoReflect.Descriptor instead.
func (*ProcessedMark) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{14}
}

func (x *ProcessedMark) GetRawObservationId() string {
	if x != nil {
		return x.RawObservationId
	}
	return ""
}

func (x *ProcessedMark) GetTranslationBatch() string {
	if x != nil {
		return x.TranslationBatch
	}
	return ""
}

type Run struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{15}
}

func (x *Run) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Run) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Run) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Run) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type SessionDescriptor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Endpoint        *SessionEndpoint       `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Scope           *Scope                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	ScopeHash       string                 `protobuf:"bytes,4,opt,name=scope_hash,json=scopeHash,proto3" json:"scope_hash,omitempty"`
	ScopeGeneration uint64                 `protobuf:"varint,5,opt,name=scope_generation,json=scopeGeneration,proto3" json:"scope_generation,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionDescriptor) Reset() {
	*x = SessionDescriptor{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionDescriptor) ProtoMessage() {}

func (x *SessionDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionDescriptor.ProtoReflect.Descriptor instead.
func (*SessionDescriptor) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{16}
}

func (x *SessionDescriptor) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionDescriptor) GetEndpoint() *SessionEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *SessionDescriptor) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *SessionDescriptor) GetScopeHash() string {
	if x != nil {
		return x.ScopeHash
	}
	return ""
}

func (x *SessionDescriptor) GetScopeGeneration() uint64 {
	if x != nil {
		return x.ScopeGeneration
	}
	return 0
}

func (x *SessionDescriptor) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PutSessionDescriptorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descriptor_   *SessionDescriptor     `protobuf:"bytes,1,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutSessionDescriptorRequest) Reset() {
	*x = PutSessionDescriptorRequest{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutSessionDescriptorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutSessionDescriptorRequest) ProtoMessage() {}

func (x *PutSessionDescriptorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutSessionDescriptorRequest.ProtoReflect.Descriptor instead.
func (*PutSessionDescriptorRequest) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{17}
}

func (x *PutSessionDescriptorRequest) GetDescriptor_() *SessionDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

type ListSessionDescriptorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionDescriptorsRequest) Reset() {
	*x = ListSessionDescriptorsRequest{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionDescriptorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionDescriptorsRequest) ProtoMessage() {}

func (x *ListSessionDescriptorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionDescriptorsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionDescriptorsRequest) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{18}
}

func (x *ListSessionDescriptorsRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type ListSessionDescriptorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descriptors   []*SessionDescriptor   `protobuf:"bytes,1,rep,name=descriptors,proto3" json:"descriptors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionDescriptorsResponse) Reset() {
	*x = ListSessionDescriptorsResponse{}
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionDescriptorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionDescriptorsResponse) ProtoMessage() {}

func (x *ListSessionDescriptorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionDescriptorsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionDescriptorsResponse) Descriptor() ([]byte, []int) {
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP(), []int{19}
}

func (x *ListSessionDescriptorsResponse) GetDescriptors() []*SessionDescriptor {
	if x != nil {
		return x.Descriptors
	}
	return nil
}

var File_botfam_eventdelivery_v2_eventdelivery_proto protoreflect.FileDescriptor

const file_botfam_eventdelivery_v2_eventdelivery_proto_rawDesc = "" +
	"\n" +
	"+botfam/eventdelivery/v2/eventdelivery.proto\x12\x17botfam.eventdelivery.v2\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"~\n" +
	"\x05Scope\x12\x1d\n" +
	"\n" +
	"repo_owner\x18\x01 \x01(\tR\trepoOwner\x12\x1b\n" +
	"\trepo_name\x18\x02 \x01(\tR\brepoName\x12!\n" +
	"\fmilestone_id\x18\x03 \x01(\x03R\vmilestoneId\x12\x16\n" +
	"\x06labels\x18\x04 \x03(\tR\x06labels\"\x9b\x01\n" +
	"\x0fSessionEndpoint\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12#\n" +
	"\rfencing_token\x18\x05 \x01(\x04R\ffencingToken\"\x9c\x01\n" +
	"\x0eAcquireRequest\x124\n" +
	"\x05scope\x18\x01 \x01(\v2\x1e.botfam.eventdelivery.v2.ScopeR\x05scope\x12'\n" +
	"\x0fholder_identity\x18\x02 \x01(\tR\x0eholderIdentity\x12+\n" +
	"\x03ttl\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\")\n" +
	"\fRenewRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\"+\n" +
	"\x0eReleaseRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\"\x9c\x01\n" +
	"\x05Grant\x12\x18\n" +
	"\agranted\x18\x01 \x01(\bR\agranted\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"a\n" +
	"\fWorkerStream\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x124\n" +
	"\x05scope\x18\x02 \x01(\v2\x1e.botfam.eventdelivery.v2.ScopeR\x05scope\"\xa0\x01\n" +
	"\bWorkItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12)\n" +
	"\x10scope_generation\x18\x06 \x01(\x04R\x0fscopeGeneration\"j\n" +
	"\bArtifact\x12 \n" +
	"\fwork_item_id\x18\x01 \x01(\tR\n" +
	"workItemId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\"\xd4\x01\n" +
	"\x04Span\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12!\n" +
	"\fpayload_json\x18\x05 \x01(\tR\vpayloadJson\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x92\x01\n" +
	"\vForgeAction\x12 \n" +
	"\fwork_item_id\x18\x01 \x01(\tR\n" +
	"workItemId\x12\x1d\n" +
	"\n" +
	"action_key\x18\x02 \x01(\tR\tactionKey\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x04 \x01(\tR\rargumentsJson\"\x85\x01\n" +
	"\tActionAck\x12\x1c\n" +
	"\tcommitted\x18\x01 \x01(\bR\tcommitted\x12\x18\n" +
	"\adeduped\x18\x02 \x01(\bR\adeduped\x12\x1b\n" +
	"\toutbox_id\x18\x03 \x01(\tR\boutboxId\x12#\n" +
	"\rresponse_json\x18\x04 \x01(\tR\fresponseJson\"q\n" +
	"\x0eObserveRequest\x124\n" +
	"\x05scope\x18\x01 \x01(\v2\x1e.botfam.eventdelivery.v2.ScopeR\x05scope\x12)\n" +
	"\x10scope_generation\x18\x02 \x01(\x04R\x0fscopeGeneration\"\xd9\x02\n" +
	"\x0eRawObservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x12\n" +
	"\x04repo\x18\x03 \x01(\tR\x04repo\x12#\n" +
	"\rartifact_kind\x18\x04 \x01(\tR\fartifactKind\x12'\n" +
	"\x0fartifact_number\x18\x05 \x01(\x03R\x0eartifactNumber\x12\x1d\n" +
	"\n" +
	"event_kind\x18\x06 \x01(\tR\teventKind\x12\x1b\n" +
	"\tevent_key\x18\a \x01(\tR\beventKey\x12!\n" +
	"\fsource_query\x18\b \x01(\tR\vsourceQuery\x12!\n" +
	"\fpayload_json\x18\t \x01(\tR\vpayloadJson\x12;\n" +
	"\vobserved_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"j\n" +
	"\rProcessedMark\x12,\n" +
	"\x12raw_observation_id\x18\x01 \x01(\tR\x10rawObservationId\x12+\n" +
	"\x11translation_batch\x18\x02 \x01(\tR\x10translationBatch\"\xae\x01\n" +
	"\x03Run\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\x90\x02\n" +
	"\x11SessionDescriptor\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12D\n" +
	"\bendpoint\x18\x02 \x01(\v2(.botfam.eventdelivery.v2.SessionEndpointR\bendpoint\x124\n" +
	"\x05scope\x18\x03 \x01(\v2\x1e.botfam.eventdelivery.v2.ScopeR\x05scope\x12\x1d\n" +
	"\n" +
	"scope_hash\x18\x04 \x01(\tR\tscopeHash\x12)\n" +
	"\x10scope_generation\x18\x05 \x01(\x04R\x0fscopeGeneration\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"i\n" +
	"\x1bPutSessionDescriptorRequest\x12J\n" +
	"\n" +
	"descriptor\x18\x01 \x01(\v2*.botfam.eventdelivery.v2.SessionDescriptorR\n" +
	"descriptor\"U\n" +
	"\x1dListSessionDescriptorsRequest\x124\n" +
	"\x05scope\x18\x01 \x01(\v2\x1e.botfam.eventdelivery.v2.ScopeR\x05scope\"n\n" +
	"\x1eListSessionDescriptorsResponse\x12L\n" +
	"\vdescriptors\x18\x01 \x03(\v2*.botfam.eventdelivery.v2.SessionDescriptorR\vdescriptors2f\n" +
	"\x0fSessionResolver\x12S\n" +
	"\aResolve\x12\x1e.botfam.eventdelivery.v2.Scope\x1a(.botfam.eventdelivery.v2.SessionEndpoint2\xf7\x01\n" +
	"\x05Lease\x12R\n" +
	"\aAcquire\x12'.botfam.eventdelivery.v2.AcquireRequest\x1a\x1e.botfam.eventdelivery.v2.Grant\x12N\n" +
	"\x05Renew\x12%.botfam.eventdelivery.v2.RenewRequest\x1a\x1e.botfam.eventdelivery.v2.Grant\x12J\n" +
	"\aRelease\x12'.botfam.eventdelivery.v2.ReleaseRequest\x1a\x16.google.protobuf.Empty2\xe4\x02\n" +
	"\rWorkerChannel\x12Z\n" +
	"\fDispatchWork\x12%.botfam.eventdelivery.v2.WorkerStream\x1a!.botfam.eventdelivery.v2.WorkItem0\x01\x12K\n" +
	"\x0eRecordArtifact\x12!.botfam.eventdelivery.v2.Artifact\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x0fSubmitTelemetry\x12\x1d.botfam.eventdelivery.v2.Span\x1a\x16.google.protobuf.Empty(\x01\x12^\n" +
	"\x12ProposeForgeAction\x12$.botfam.eventdelivery.v2.ForgeAction\x1a\".botfam.eventdelivery.v2.ActionAck2\xa2\x02\n" +
	"\x13ObservationPipeline\x12]\n" +
	"\aObserve\x12'.botfam.eventdelivery.v2.ObserveRequest\x1a'.botfam.eventdelivery.v2.RawObservation0\x01\x12Y\n" +
	"\tTranslate\x12'.botfam.eventdelivery.v2.RawObservation\x1a!.botfam.eventdelivery.v2.WorkItem0\x01\x12Q\n" +
	"\x0fRecordProcessed\x12&.botfam.eventdelivery.v2.ProcessedMark\x1a\x16.google.protobuf.Empty2\x80\x02\n" +
	"\fSessionStore\x12d\n" +
	"\x14PutSessionDescriptor\x124.botfam.eventdelivery.v2.PutSessionDescriptorRequest\x1a\x16.google.protobuf.Empty\x12\x89\x01\n" +
	"\x16ListSessionDescriptors\x126.botfam.eventdelivery.v2.ListSessionDescriptorsRequest\x1a7.botfam.eventdelivery.v2.ListSessionDescriptorsResponseBOZMgithub.com/robertolupi/botfam/internal/eventdelivery/contract/eventdeliveryv2b\x06proto3"

var (
	file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescOnce sync.Once
	file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescData []byte
)

func file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescGZIP() []byte {
	file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescOnce.Do(func() {
		file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_botfam_eventdelivery_v2_eventdelivery_proto_rawDesc), len(file_botfam_eventdelivery_v2_eventdelivery_proto_rawDesc)))
	})
	return file_botfam_eventdelivery_v2_eventdelivery_proto_rawDescData
}

var file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_botfam_eventdelivery_v2_eventdelivery_proto_goTypes = []any{
	(*Scope)(nil),                          // 0: botfam.eventdelivery.v2.Scope
	(*SessionEndpoint)(nil),                // 1: botfam.eventdelivery.v2.SessionEndpoint
	(*AcquireRequest)(nil),                 // 2: botfam.eventdelivery.v2.AcquireRequest
	(*RenewRequest)(nil),                   // 3: botfam.eventdelivery.v2.RenewRequest
	(*ReleaseRequest)(nil),                 // 4: botfam.eventdelivery.v2.ReleaseRequest
	(*Grant)(nil),                          // 5: botfam.eventdelivery.v2.Grant
	(*WorkerStream)(nil),                   // 6: botfam.eventdelivery.v2.WorkerStream
	(*WorkItem)(nil),                       // 7: botfam.eventdelivery.v2.WorkItem
	(*Artifact)(nil),                       // 8: botfam.eventdelivery.v2.Artifact
	(*Span)(nil),                           // 9: botfam.eventdelivery.v2.Span
	(*ForgeAction)(nil),                    // 10: botfam.eventdelivery.v2.ForgeAction
	(*ActionAck)(nil),                      // 11: botfam.eventdelivery.v2.ActionAck
	(*ObserveRequest)(nil),                 // 12: botfam.eventdelivery.v2.ObserveRequest
	(*RawObservation)(nil),                 // 13: botfam.eventdelivery.v2.RawObservation
	(*ProcessedMark)(nil),                  // 14: botfam.eventdelivery.v2.ProcessedMark
	(*Run)(nil),                            // 15: botfam.eventdelivery.v2.Run
	(*SessionDescriptor)(nil),              // 16: botfam.eventdelivery.v2.SessionDescriptor
	(*PutSessionDescriptorRequest)(nil),    // 17: botfam.eventdelivery.v2.PutSessionDescriptorRequest
	(*ListSessionDescriptorsRequest)(nil),  // 18: botfam.eventdelivery.v2.ListSessionDescriptorsRequest
	(*ListSessionDescriptorsResponse)(nil), // 19: botfam.eventdelivery.v2.ListSessionDescriptorsResponse
	(*durationpb.Duration)(nil),            // 20: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),          // 21: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 22: google.protobuf.Empty
}
var file_botfam_eventdelivery_v2_eventdelivery_proto_depIdxs = []int32{
	0,  // 0: botfam.eventdelivery.v2.AcquireRequest.scope:type_name -> botfam.eventdelivery.v2.Scope
	20, // 1: botfam.eventdelivery.v2.AcquireRequest.ttl:type_name -> google.protobuf.Duration
	21, // 2: botfam.eventdelivery.v2.Grant.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 3: botfam.eventdelivery.v2.WorkerStream.scope:type_name -> botfam.eventdelivery.v2.Scope
	21, // 4: botfam.eventdelivery.v2.Span.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 5: botfam.eventdelivery.v2.ObserveRequest.scope:type_name -> botfam.eventdelivery.v2.Scope
	21, // 6: botfam.eventdelivery.v2.RawObservation.observed_at:type_name -> google.protobuf.Timestamp
	21, // 7: botfam.eventdelivery.v2.Run.started_at:type_name -> google.protobuf.Timestamp
	21, // 8: botfam.eventdelivery.v2.Run.completed_at:type_name -> google.protobuf.Timestamp
	1,  // 9: botfam.eventdelivery.v2.SessionDescriptor.endpoint:type_name -> botfam.eventdelivery.v2.SessionEndpoint
	0,  // 10: botfam.eventdelivery.v2.SessionDescriptor.scope:type_name -> botfam.eventdelivery.v2.Scope
	16, // 11: botfam.eventdelivery.v2.PutSessionDescriptorRequest.descriptor:type_name -> botfam.eventdelivery.v2.SessionDescriptor
	0,  // 12: botfam.eventdelivery.v2.ListSessionDescriptorsRequest.scope:type_name -> botfam.eventdelivery.v2.Scope
	16, // 13: botfam.eventdelivery.v2.ListSessionDescriptorsResponse.descriptors:type_name -> botfam.eventdelivery.v2.SessionDescriptor
	0,  // 14: botfam.eventdelivery.v2.SessionResolver.Resolve:input_type -> botfam.eventdelivery.v2.Scope
	2,  // 15: botfam.eventdelivery.v2.Lease.Acquire:input_type -> botfam.eventdelivery.v2.AcquireRequest
	3,  // 16: botfam.eventdelivery.v2.Lease.Renew:input_type -> botfam.eventdelivery.v2.RenewRequest
	4,  // 17: botfam.eventdelivery.v2.Lease.Release:input_type -> botfam.eventdelivery.v2.ReleaseRequest
	6,  // 18: botfam.eventdelivery.v2.WorkerChannel.DispatchWork:input_type -> botfam.eventdelivery.v2.WorkerStream
	8,  // 19: botfam.eventdelivery.v2.WorkerChannel.RecordArtifact:input_type -> botfam.eventdelivery.v2.Artifact
	9,  // 20: botfam.eventdelivery.v2.WorkerChannel.SubmitTelemetry:input_type -> botfam.eventdelivery.v2.Span
	10, // 21: botfam.eventdelivery.v2.WorkerChannel.ProposeForgeAction:input_type -> botfam.eventdelivery.v2.ForgeAction
	12, // 22: botfam.eventdelivery.v2.ObservationPipeline.Observe:input_type -> botfam.eventdelivery.v2.ObserveRequest
	13, // 23: botfam.eventdelivery.v2.ObservationPipeline.Translate:input_type -> botfam.eventdelivery.v2.RawObservation
	14, // 24: botfam.eventdelivery.v2.ObservationPipeline.RecordProcessed:input_type -> botfam.eventdelivery.v2.ProcessedMark
	17, // 25: botfam.eventdelivery.v2.SessionStore.PutSessionDescriptor:input_type -> botfam.eventdelivery.v2.PutSessionDescriptorRequest
	18, // 26: botfam.eventdelivery.v2.SessionStore.ListSessionDescriptors:input_type -> botfam.eventdelivery.v2.ListSessionDescriptorsRequest
	1,  // 27: botfam.eventdelivery.v2.SessionResolver.Resolve:output_type -> botfam.eventdelivery.v2.SessionEndpoint
	5,  // 28: botfam.eventdelivery.v2.Lease.Acquire:output_type -> botfam.eventdelivery.v2.Grant
	5,  // 29: botfam.eventdelivery.v2.Lease.Renew:output_type -> botfam.eventdelivery.v2.Grant
	22, // 30: botfam.eventdelivery.v2.Lease.Release:output_type -> google.protobuf.Empty
	7,  // 31: botfam.eventdelivery.v2.WorkerChannel.DispatchWork:output_type -> botfam.eventdelivery.v2.WorkItem
	22, // 32: botfam.eventdelivery.v2.WorkerChannel.RecordArtifact:output_type -> google.protobuf.Empty
	22, // 33: botfam.eventdelivery.v2.WorkerChannel.SubmitTelemetry:output_type -> google.protobuf.Empty
	11, // 34: botfam.eventdelivery.v2.WorkerChannel.ProposeForgeAction:output_type -> botfam.eventdelivery.v2.ActionAck
	13, // 35: botfam.eventdelivery.v2.ObservationPipeline.Observe:output_type -> botfam.eventdelivery.v2.RawObservation
	7,  // 36: botfam.eventdelivery.v2.ObservationPipeline.Translate:output_type -> botfam.eventdelivery.v2.WorkItem
	22, // 37: botfam.eventdelivery.v2.ObservationPipeline.RecordProcessed:output_type -> google.protobuf.Empty
	22, // 38: botfam.eventdelivery.v2.SessionStore.PutSessionDescriptor:output_type -> google.protobuf.Empty
	19, // 39: botfam.eventdelivery.v2.SessionStore.ListSessionDescriptors:output_type -> botfam.eventdelivery.v2.ListSessionDescriptorsResponse
	27, // [27:40] is the sub-list for method output_type
	14, // [14:27] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_botfam_eventdelivery_v2_eventdelivery_proto_init() }
func file_botfam_eventdelivery_v2_eventdelivery_proto_init() {
	if File_botfam_eventdelivery_v2_eventdelivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_botfam_eventdelivery_v2_eventdelivery_proto_rawDesc), len(file_botfam_eventdelivery_v2_eventdelivery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_botfam_eventdelivery_v2_eventdelivery_proto_goTypes,
		DependencyIndexes: file_botfam_eventdelivery_v2_eventdelivery_proto_depIdxs,
		MessageInfos:      file_botfam_eventdelivery_v2_eventdelivery_proto_msgTypes,
	}.Build()
	File_botfam_eventdelivery_v2_eventdelivery_proto = out.File
	file_botfam_eventdelivery_v2_eventdelivery_proto_goTypes = nil
	file_botfam_eventdelivery_v2_eventdelivery_proto_depIdxs = nil
}
